stages:
  - test


include:
  #set environment variables
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/before.inc.yml'
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/after.inc.yml'
  # python tests 
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/special_tests.inc.yml'
  # linking against ELPA tests
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/project_tests.inc.yml'
  # ELPA tests
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/generated_tests.inc.yml'
  # layout tests
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/layout_tests.inc.yml'
  # hip_on_nvidia
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/hip_on_nvidia_tests.inc.yml'
  # nvhpcsdk tests
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/nvhpcsdk_tests.inc.yml'
  # sycl on cpu tests
  - remote: 'https://gitlab.mpcdf.mpg.de/elpa/elpa_ci/raw/main/sycl_on_cpu_tests.inc.yml'








