name: ELPA Xe Performance Dashboard
on:
  - workflow_dispatch
jobs:
  dashboard:
    strategy:
      fail-fast: false
      matrix:
        numbers:
          - real
#         - complex
        problem-size:
          - 1000
#         - 10000
#         - 15000
#         - 20000
        config:
          - arch: pvc
            ranks: 2
            slurm-partition: QZ1J-ICX-PVC
            runner: ortce-skl22_2

#         - build-script: .github/scripts/build_elpa.sh pvc
#           run-script: .github/scripts/run_elpa.sh pvc
#           verify-script: .github/scripts/parseOutput.py
#           metrics-script: .github/scripts/parseOutput.py
#           slurm-partition: QZ1J-ICX-PVC
#           runner: ortce-skl22_2 # If we are on the same runner, there may be a conflict with the build artifacts (bah!)
    uses: intel-sandbox/xcss-workflows/.github/workflows/xe-performance-dashboard.yml@main
    with:
      application: ELPA
      build-script: .github/scripts/build_elpa.sh ${{ matrix.config.arch }}
      run-script: .github/scripts/run_elpa.sh ${{ matrix.config.arch }} ${{ matrix.problem-size }} ${{ matrix.numbers }} ${{ matrix.config.ranks }}
      verify-script: .github/scripts/parseOutput.py -v build_${{ matrix.config.arch }}/elpa_${{ matrix.numbers }}_${{ matrix.config.arch }}_${{ matrix.config.ranks }}_${{ matrix.problem-size }}.txt
      metrics-script: ${{ matrix.config.metrics-script }} -p -i None -w AlfVen result.log
      slurm-partition: ${{ matrix.config.slurm-partition }}
      runs-on: ${{ matrix.config.runner }}
