name: ELPA Xe Performance Dashboard

on:
  workflow_dispatch:
    inputs:
      cpa-config:
        description: 'cpa-config (the .sh file, not the .yml file)'
        required: false
        default: ''

jobs:
  dashboard:
    strategy:
      fail-fast: false
      matrix:
        numbers:
          - real
          - complex
        problem-size:
          - 10000
        config:
          - arch: pvc-1100
            ranks: 1
            runner: pvc
            slurm-partition: Q24Q-SPR-PVC
          - arch: pvc
            ranks: 1
            runner: pvc
            slurm-partition: QZ1J-SPR-PVC
          - arch: pvc
            ranks: 2
            runner: pvc
            slurm-partition: QZ1J-SPR-PVC
          - arch: pvc
            ranks: 8
            runner: pvc
            slurm-partition: QZ1B-SPR-4oam-PVC
          - arch: a100
            ranks: 2
            runner: pvc
            slurm-partition: a100-80G
          - arch: h100
            ranks: 2
            runner: pvc
            slurm-partition: H100
#         - arch: spr
#           ranks: 224
#           runner: pvc
#           slurm-partition: QZ1J-SPR-PVC
    uses: intel-sandbox/xcss-workflows/.github/workflows/xe-performance-dashboard.yml@main
    with:
      application: elpa
      build-script: .github/scripts/build_elpa.sh ${{ matrix.config.arch }} ${{ matrix.problem-size }} ${{ matrix.numbers }} ${{ matrix.config.ranks }}
      run-script: .github/scripts/run_elpa.sh ${{ matrix.config.arch }} ${{ matrix.problem-size }} ${{ matrix.numbers }} ${{ matrix.config.ranks }}
      verify-script: .github/scripts/parseOutput.py -v cpa_results/elpa_${{ matrix.numbers }}_${{ matrix.config.arch }}_${{ matrix.config.ranks }}_${{ matrix.problem-size }}.txt
      metrics-script: .github/scripts/parseOutput.py -p -i ${{ matrix.numbers }}_${{ matrix.config.arch }}_${{ matrix.config.ranks }} -w ${{ matrix.numbers }}_${{ matrix.problem-size }} cpa_results/elpa_${{ matrix.numbers }}_${{ matrix.config.arch }}_${{ matrix.config.ranks }}_${{ matrix.problem-size }}.txt
      slurm-partition: ${{ matrix.config.slurm-partition }}
      hpcwl-dir: /hpc-wl-automation
      runs-on: ${{ matrix.config.runner }}
      cpa-config: ${{ inputs.cpa-config }}
