name: ELPA Xe Performance Dashboard
on:
  - workflow_dispatch
  - push:
    branches: ["intel-main"]
jobs:
  dashboard:
    strategy:
      fail-fast: false
      matrix:
        config:
          - build-script: .github/scripts/build_elpa.sh pvc
            run-script: .github/scripts/run_elpa.sh pvc
            verify-script: .github/scripts/parseOutput.py
            metrics-script: .github/scripts/parseOutput.py
            slurm-partition: QZ1J-ICX-PVC
            runner: ortce-skl22_2 # If we are on the same runner, there may be a conflict with the build artifacts (bah!)
#         - build-script: .github/scripts/build_dpecho_pvc.sh
#           run-script: .github/scripts/run_dpecho_pvc.sh 2t
#           verify-script: .github/scripts/parseOutput.py
#           metrics-script: .github/scripts/parseOutput.py
#           slurm-partition: QZ1J-ICX-PVC
#           runner: ortce-skl22_3 # If we are on the same runner, there may be a conflict with the build artifacts (bah!)
#         - build-script: .github/scripts/build_dpecho_pvc_mpi.sh
#           run-script: .github/scripts/run_dpecho_pvc.sh es8t
#           verify-script: .github/scripts/parseOutput.py -r 8
#           metrics-script: .github/scripts/parseOutput.py
#           slurm-partition: QZ1B-SPR-4oam-PVC
#           runner: ortce-skl22 # If we are on the same runner, there may be a conflict with the build artifacts (bah!)
#         - build-script: .github/scripts/build_dpecho_icx.sh
#           run-script: .github/scripts/run_dpecho_icx.sh
#           verify-script: .github/scripts/parseOutput.py
#           metrics-script: .github/scripts/parseOutput.py
#           slurm-partition: QZ1J-ICX-PVC
#           runner: ortce-skl22_4 # If we are on the same runner, there may be a conflict with the build artifacts (bah!)
#         - build-script: .github/scripts/build_dpecho_a100.sh
#           run-script: .github/scripts/run_dpecho_a100.sh
#           verify-script: .github/scripts/parseOutput.py
#           metrics-script: .github/scripts/parseOutput.py
#           slurm-partition: a100-80G
#           runner: ortce-skl22
#         - build-script: .github/scripts/build_dpecho_h100.sh
#           run-script: .github/scripts/run_dpecho_h100.sh
#           verify-script: .github/scripts/parseOutput.py
#           metrics-script: .github/scripts/parseOutput.py
#           slurm-partition: H100
#           runner: ortce-skl22
    uses: intel-sandbox/xcss-workflows/.github/workflows/xe-performance-dashboard.yml@main
    with:
      application: DPEcho
      build-script: ${{ matrix.config.build-script }}
      run-script: ${{ matrix.config.run-script }}
      verify-script: ${{ matrix.config.verify-script }} -v result.log
      metrics-script: ${{ matrix.config.metrics-script }} -p -i None -w AlfVen result.log
      slurm-partition: ${{ matrix.config.slurm-partition }}
      runs-on: ${{ matrix.config.runner }}
